
language: node_js
node_js:
- 6.11.2
env:
- CXX=g++-4.8
before_script:
  - npm install -g gulp-cli
script: gulp
deploy:
  - provider: pages
    github_token: $GITHUB_AMBER_ROCKWOOD
    skip_cleanup: true
    local_dir: dist
    on:
      branch: master
